-- Creates a least-privilege role/user for the Procurement AI Streamlit app
-- Run as ACCOUNTADMIN (or a role with CREATE USER/ROLE + MANAGE GRANTS privileges)

CREATE ROLE IF NOT EXISTS STREAMLIT_APP_ROLE;

CREATE USER IF NOT EXISTS STREAMLIT_APP_USER
    PASSWORD = '<set-a-strong-password-here>'
    DEFAULT_ROLE = STREAMLIT_APP_ROLE
    DEFAULT_WAREHOUSE = COMPUTE_WH
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE STREAMLIT_APP_ROLE TO USER STREAMLIT_APP_USER;

-- Warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE STREAMLIT_APP_ROLE;

-- Database / schema access
GRANT USAGE ON DATABASE SAP_P2P_FINANCE_DEV TO ROLE STREAMLIT_APP_ROLE;
GRANT USAGE ON SCHEMA SAP_P2P_FINANCE_DEV.GOLD TO ROLE STREAMLIT_APP_ROLE;

-- Read access on GOLD schema (current + future objects)
GRANT SELECT ON ALL TABLES IN SCHEMA SAP_P2P_FINANCE_DEV.GOLD TO ROLE STREAMLIT_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAP_P2P_FINANCE_DEV.GOLD TO ROLE STREAMLIT_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SAP_P2P_FINANCE_DEV.GOLD TO ROLE STREAMLIT_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAP_P2P_FINANCE_DEV.GOLD TO ROLE STREAMLIT_APP_ROLE;
