SNOWFLAKE_ACCOUNT = "pxcidas-jb84419"
SNOWFLAKE_USER = "administrator"
SNOWFLAKE_PASSWORD = "$Uccess^^909910"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "SAP_P2P_FINANCE_DEV"
SNOWFLAKE_SCHEMA = "GOLD"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
