SNOWFLAKE_ACCOUNT = "hdomnon-ot29996"
SNOWFLAKE_USER = "STREAMLIT_APP_USER"
SNOWFLAKE_PASSWORD = "aQdp9zd1sH0M4x2QkVi1QWis!Aa1"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "SAP_P2P_FINANCE_DEV"
SNOWFLAKE_SCHEMA = "GOLD"
SNOWFLAKE_ROLE = "STREAMLIT_APP_ROLE"

